# Generated by Django 4.2 on 2023-04-11 10:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Posting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_content', models.TextField()),
                ('create_at', models.DateField(auto_now_add=True)),
                ('title', models.CharField(max_length=256)),
                ('update_at', models.DateField(auto_now=True)),
                ('category', models.CharField(choices=[('codereview', '코드리뷰'), ('course', '취업진로'), ('coding_study', '개발공부'), ('study', '스터디'), ('free_board', '잡담')], max_length=256)),
                ('post_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posting.posting')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
