# Generated by Django 4.2 on 2023-04-16 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Posting',
            fields=[
                ('posting_id', models.IntegerField(primary_key=True, serialize=False)),
                ('main_content', models.TextField(null=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=256)),
                ('update_at', models.DateField(auto_now=True)),
                ('category', models.CharField(choices=[('codereview', '코드리뷰'), ('course', '취업진로'), ('coding_study', '개발공부'), ('study', '스터디'), ('free_board', '잡담')], max_length=256)),
            ],
        ),
    ]
