# Generated by Django 4.2 on 2023-04-12 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posting',
            name='id',
        ),
        migrations.AlterField(
            model_name='posting',
            name='main_content',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='posting',
            name='post_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
