# Generated by Django 4.2 on 2023-04-16 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('comment_id', models.IntegerField(primary_key=True, serialize=False)),
                ('update_at', models.DateField(auto_now=True)),
                ('create_at', models.DateField(auto_now_add=True)),
                ('comment_content', models.TextField(null=True)),
            ],
            options={
                'db_table': 'comments',
            },
        ),
    ]
