# Generated by Django 4.2 on 2023-04-14 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='commnt_content',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='post_id',
        ),
        migrations.AddField(
            model_name='comment',
            name='comment_content',
            field=models.TextField(null=True),
        ),
        migrations.AlterModelTable(
            name='comment',
            table='comments',
        ),
    ]
